"""
Train the SIMShield SIM-swap Random Forest on the REAL 100k-row dataset.

    python train_model.py

Unlike the earlier prototype (which trained on ~4k rows it generated itself),
SIMShield trains on sim_swap_fraud_dataset_100000.csv - 100,000 synthetic
telecom records with 11 features (see config.yaml -> ml.features). It prints a
full evaluation, writes the model to models/rf_model.joblib, and emits a MODEL
CARD (models/model_card.md) documenting data, metrics and intended use - part of
the project's transparency/ethics commitment.
"""
import csv
import os
from datetime import date

import joblib
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import (classification_report, confusion_matrix,
                             precision_recall_fscore_support, roc_auc_score)
from sklearn.model_selection import cross_val_score, train_test_split

from engine.config_loader import backend_path, load_config


def load_dataset(cfg):
    path = backend_path(cfg["ml"]["dataset_path"])
    features = cfg["ml"]["features"]
    target = cfg["ml"]["target_column"]
    X, y = [], []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            X.append([float(row[name]) for name in features])
            y.append(int(float(row[target])))
    return X, y, features


def write_model_card(cfg, features, importances, metrics, n_rows):
    card = f"""# SIMShield Model Card

*Generated by `train_model.py` on {date.today().isoformat()}.*

> ## ⚠️ NOT VALIDATED FOR DEPLOYMENT
> This model is trained on **synthetic data with a ~74% fraud base rate**. A real
> deployment sees under 1%. Accuracy on this dataset is therefore uninformative
> and every metric below is optimistic by construction. The operator signals it
> consumes (IMSI/ICCID change, SIM age, SIM location) are **simulated** — no
> operator agreement exists. Do not present these figures as evidence of
> real-world performance.
>
> Run `python evaluate_ml.py` for the honest evaluation: PR-AUC, false-positive
> rate, calibration, bootstrap confidence intervals, component ablations and an
> adversarial suite, computed on a held-out split never used for tuning.
>
> **Artefact integrity:** the `.joblib` files are hashed into
> `models/manifest.json` and verified before loading, because unpickling an
> untrusted artefact is arbitrary code execution.

## Model
- **Type:** RandomForestClassifier (scikit-learn), 300 trees, max_depth=12,
  `class_weight="balanced"`.
- **Task:** Binary classification - P(SIM-swap fraud) for a banking login.
- **Output:** calibrated-ish probability in [0, 1], fused with the rule and
  behavioral components in `engine/detector.py` (it is never the sole decider).

## Training data
- **Source:** `sim_swap_fraud_dataset_100000.csv` - {n_rows:,} SYNTHETIC telecom
  records. No real customer or operator data is used.
- **Features ({len(features)}):** {", ".join(features)}.
- **Target:** `{cfg['ml']['target_column']}` (1 = fraud).
- **Split:** 75% train / 25% stratified test, `random_state=42`.

## Performance — TRAINING-TIME figures, not the authoritative evaluation

> **Which numbers to quote.** These come from this script's own 75/25 split,
> computed immediately after fitting. They are *not* the evaluation to cite.
> `evaluate_ml.py` uses a **three-way 60/20/20 split** whose held-out fifth is
> touched exactly once and never used for any tuning decision — that is the
> honest measurement, and where the two disagree, **`evaluate_ml.py` is the one
> to report.** Both are kept because the difference between them is itself a
> finding: an optimistic split flatters the model.

- **Accuracy:** {metrics['accuracy']:.3f}
- **Precision (fraud):** {metrics['precision']:.3f}
- **Recall (fraud):** {metrics['recall']:.3f}
- **F1 (fraud):** {metrics['f1']:.3f}
- **ROC-AUC:** {metrics['roc_auc']:.3f}
- **5-fold CV ROC-AUC:** {metrics['cv_auc_mean']:.3f} +/- {metrics['cv_auc_std']:.3f}
- **Confusion matrix [[TN, FP], [FN, TP]]:** {metrics['confusion']}

> A ROC-AUC of 1.000 and a cross-validated standard deviation of 0.000 are not
> achievements — they are symptoms. The synthetic generator makes the classes
> almost linearly separable on four binary flags, so the task is far easier than
> the real one. Report PR-AUC and the false-positive rate instead; ROC-AUC is
> close to meaningless at a 74% positive rate.

## Feature importance
""" + "\n".join(f"- `{n}`: {imp:.3f}" for n, imp in importances) + f"""

## Operator data dependency
One fused input — `sim_location_mismatch`, the network-reported SIM area versus
the location a login claims — would come from a mobile operator in production.

**It is SIMULATED.** SIMShield holds no operator agreement, no credentials, and
has never contacted a network. It is produced by `MockOperatorAdapter` from
synthetic fixtures; the CAMARA adapter (`engine/operator_camara.py`) is a
non-operational placeholder that always returns `NOT_CONFIGURED` and contains no
HTTP client, endpoint or credential. No figure in this card is evidence about a
real telecom feed.

**Degradation is measured, not assumed** (`python evaluate_operator.py`). The
scenario suite is re-scored under nine operator conditions — available,
unavailable, timeout, stale, partial, disagreement, rate-limited, malformed,
consent-withdrawn:

| Property | Result |
|---|---|
| Decisions that became MORE restrictive under degradation | **0 / 360** |
| Isolating probe, operator available | 26.3 → VERIFY |
| Isolating probe, each degraded condition | 6.8 → ALLOW (−19.5) |

Failing open is structural: the mismatch flag is computed only on the `usable`
branch, and there is no `fail_open` configuration key to disable it.

*Caveat on the suite:* the 40 scenarios cannot measure this feature on their own.
The one operator-dependent scenario also fires eight other flags whose raw points
(305) already exceed the behavioural cap (100), so removing the 65-point mismatch
flag moves its score by zero. The isolating probes exist because without them the
matrix would pass vacuously.

## Accuracy measured from human labels
The figures above are scored against labels the synthetic generator produced —
the model marked by the process that wrote its exam. A second, independent
measurement exists: `engine/feedback.py` derives a false-positive rate from
**analyst-coded case outcomes** (`reason_codes.yaml`), where the label came from
a person examining evidence.

The two are **not comparable**:

| | Dataset FPR | Human-labelled FPR |
|---|---|---|
| Label source | Synthetic generator | Analyst reviewing a case |
| Denominator | All held-out rows | Only decisions someone reviewed |
| Bias | Marked by its own generator | Self-selected — people who give up are invisible |
| Reading | Internal consistency | **Lower bound** on the true burden |

The human-labelled rate is reported as `null` below 20 reviewed outcomes rather
than as a percentage with a warning attached.

## Fairness analysis
An earlier version of this card stated that no fairness analysis was possible.
One now exists — with a caveat that must travel with every number it produces.

**The cohort attributes are FICTIONAL**, attached to synthetic profiles
(`synthetic_cohort` in `data/users/*.json`, each carrying an explicit `_note`)
purely so the analysis has groups to compare. No demographic data is collected
from any real person. This demonstrates that the measurement works; it is **not**
a finding about real subscribers.

Measured: selection rate (VERIFY+BLOCK) per cohort across operator, age band,
region and settlement; the four-fifths disparate-impact ratio; and upheld appeals
by cohort. Cohorts below 30 decisions report **no rate at all**, and are excluded
from the ratio rather than counted as zero.

**The monitors are validated against ground truth known by construction**
(`python evaluate_monitoring.py`): identical distributions → stable; +15 mean
shift → significant; variance collapse → significant; even cohort split → no
flag; 3:1 disparity → flagged; cohort of 3 → no rate emitted. **9/9 pass.** On
this deployment every live figure correctly reports insufficient data — that is
the intended output at this scale.

## Intended use & limits
- **Intended:** a DEFENSIVE, pre-OTP risk signal for digital-banking logins, as
  one of four fused components with human-in-the-loop escalation. It never
  decides alone.
- **Not intended:** to auto-block users on its own, to profile individuals, or
  for any use on real telecom data without a fresh DPIA and operator agreement.
- **Human oversight is a control, not an assumption.** A restrictive decision
  opens a case that must be closed with a reason code from a fixed taxonomy, and
  subscribers can appeal. The model is not authorised to be the final word.

## Known limitations
- **Unrealistic base rate.** ~74% fraud versus <1% in production. Accuracy is
  not a meaningful measure here; see PR-AUC and false-positive rate instead.
- **Near-separable labels.** The identity-change flags almost determine the
  target, so the task is easier than reality.
- **Miscalibrated in the mid range.** Predicted 0.45 corresponds to an observed
  frequency near 0.79 — usable for ranking, not as a probability.
- **Binary behavioural thresholds.** Extreme feature values do not escalate
  proportionally (9,999 logins scores much like 6). The adversarial suite prints
  this as a standing FLAG on every run.
- **Simulated operator signals.** SIM age, IMSI/ICCID change and SIM location
  are synthetic; a real feed requires a commercial operator integration, and its
  real latency, error modes and value are unknown.
- **Fairness runs on fictional cohorts**, and the human-labelled FPR on a handful
  of prototype cases. Both mechanisms are implemented and validated; neither has
  a sample that supports a conclusion.
- **Two evaluations exist.** This card's training-time split and
  `evaluate_ml.py`'s three-way split disagree, because an optimistic split
  flatters the model. Quote `evaluate_ml.py`.

## Ethical notes
- Decisions are explainable: every score ships with plain-language reasons.
- VERIFY and BLOCK escalate to a human; the model never auto-punishes.
- All identifiers in training and inference are synthetic or pseudonymised with
  a keyed HMAC.
"""
    path = backend_path("models", "model_card.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(card)
    print(f"Wrote model card -> {path}")


def main():
    cfg = load_config()
    X, y, features = load_dataset(cfg)
    print(f"Loaded {len(X):,} rows, {len(features)} features "
          f"({sum(y):,} fraud / {len(y) - sum(y):,} legit).")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y)

    clf = RandomForestClassifier(
        n_estimators=300, max_depth=12, min_samples_leaf=3,
        class_weight="balanced", n_jobs=-1, random_state=42)
    clf.fit(X_train, y_train)

    pred = clf.predict(X_test)
    proba = clf.predict_proba(X_test)[:, list(clf.classes_).index(1)]
    p, r, f1, _ = precision_recall_fscore_support(
        y_test, pred, average="binary", pos_label=1, zero_division=0)
    cm = confusion_matrix(y_test, pred).tolist()
    auc = roc_auc_score(y_test, proba)
    cv = cross_val_score(clf, X, y, cv=5, scoring="roc_auc", n_jobs=-1)

    print("\n=== Evaluation on held-out test set ===")
    print(classification_report(y_test, pred, target_names=["legit", "fraud"]))
    print(f"ROC-AUC: {auc:.3f}   5-fold CV AUC: {cv.mean():.3f} +/- {cv.std():.3f}")

    importances = sorted(zip(features, clf.feature_importances_),
                         key=lambda t: -t[1])
    print("\n=== Feature importances ===")
    for name, imp in importances:
        print(f"  {name:34s} {imp:.3f}")

    model_path = backend_path(cfg["ml"]["model_path"])
    os.makedirs(os.path.dirname(model_path), exist_ok=True)
    joblib.dump(clf, model_path)
    print(f"\nSaved model -> {model_path}")

    # --- Unsupervised companion: Isolation Forest on LEGIT rows only ---------
    # Trained without labels on normal traffic; at scoring time it flags logins
    # that look unlike anything legitimate, catching novel patterns the
    # supervised RF was never shown. (The dataset is ~74% fraud, so we fit on
    # the legit subset to model 'normal'.)
    X_legit = [x for x, label in zip(X, y) if label == 0]
    iso = IsolationForest(n_estimators=200, contamination=0.05,
                          random_state=42, n_jobs=-1)
    iso.fit(X_legit)
    iso_path = backend_path(cfg["ml"].get("iso_model_path", "models/iso_model.joblib"))
    joblib.dump(iso, iso_path)
    print(f"Saved Isolation Forest (unsupervised, {len(X_legit):,} legit rows) -> {iso_path}")

    # Record artefact hashes so the engine can verify them before unpickling.
    from datetime import datetime as _dt

    from engine import artifacts
    manifest = artifacts.write_manifest(
        [model_path, iso_path],
        extra={"generated_at": _dt.now().isoformat(timespec="seconds"),
               "generated_by": "train_model.py",
               "dataset": os.path.basename(cfg["ml"]["dataset_path"])})
    print(f"Wrote integrity manifest -> {artifacts.MANIFEST_PATH}")
    for name, meta in manifest["artifacts"].items():
        print(f"  {name:22s} sha256 {meta['sha256'][:16]}…")

    accuracy = sum(int(a == b) for a, b in zip(pred, y_test)) / len(y_test)
    metrics = {
        "accuracy": accuracy,
        "precision": p, "recall": r, "f1": f1, "roc_auc": auc,
        "cv_auc_mean": cv.mean(), "cv_auc_std": cv.std(), "confusion": cm,
    }
    write_model_card(cfg, features, importances, metrics, len(X))


if __name__ == "__main__":
    main()
